# Generated by Django 2.0.3 on 2018-03-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='Url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='promocion',
            name='entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
