# Generated by Django 2.0.3 on 2018-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0002_auto_20180317_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='municipio',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
