# Generated by Django 2.0.3 on 2018-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0003_promocion_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
