# Generated by Django 2.0.3 on 2018-03-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0004_auto_20180318_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='url',
            field=models.TextField(),
        ),
    ]
