# Generated by Django 2.0.3 on 2018-03-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0008_auto_20180318_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
